[Feature] added a new method get_birthdays_per_day(day: int)
theRealGetman/goitneo-python-project-team-13 pull request #3
Opened 2024-03-13 17:48 UTC by anurov-prykhodko

reused the get_birthdays_per_week method

2024-03-13 18:38 UTC, thebedcoder requested changes

2024-03-13 18:38 UTC, thebedcoder commented on main.py
> +            print(handlers.get_birthdays_per_day(args))
you can replace `birthdays` command with your function, we need only one of them :)

2024-03-13 18:38 UTC, thebedcoder commented on src/handlers.py
> +def get_birthdays_per_day(args: int) -> str:
args won't be `int` here, so this type-hinting is wrong

2024-03-13 18:38 UTC, thebedcoder commented on src/handlers.py
> +@handle_error()
please add `args_error_label` here with error text for arguments error (when user provided wrong arguments)

2024-03-13 18:38 UTC, thebedcoder commented on src/models.py
can you also modify output of this function, so that we have dates near weekdays?
For example:
```
13 Mar Wed: Bruce
15 Mar Fri: David
```

2024-03-14 15:46 UTC, thebedcoder requested changes

2024-03-14 15:46 UTC, thebedcoder commented on src/models.py
> +                birthday_date = today + timedelta(days=contact['days_delta'])
we already have birthday date for every contact, we don't need this calculations

2024-03-14 16:11 UTC, anurov-prykhodko commented on src/models.py
> +                birthday_date = today + timedelta(days=contact['days_delta'])
I don't get it.

2024-03-14 20:03 UTC, OleinikovArtem approved these changes

2024-03-15 18:05 UTC, thebedcoder requested changes

2024-03-15 18:05 UTC, thebedcoder commented on src/models.py
> +                ['{} ({})'.format(contact['name'].capitalize(), contact['birthday'].strftime('%d %b %Y')) for contact in contacts])))
let's make output like

```
Friday 15 Mar: Pug
Wednesday 20 Mar: David
```

2024-03-15 19:47 UTC, thebedcoder approved these changes

2024-03-15 19:51 UTC, merged